Add R and T components, fix correlation bugs and change minor visual stuff
marcelobianchi/sactools pull request #2
Opened 2018-05-10 19:52 UTC by IsraelDragone

VISUAL
       -correct screen resolution, now the code cat the number of screens and fix the program screen size by itself
       -magnitude position was corrected
       -creat special var to save the filters applied to S pick
    CORRELATION:
       -was inserted a var to mark if the trace was correlated
       -if one trace has different dt the code didn't break anymore, the correlation code skip this trace and warn which station is
       -both sizes of reference trace (rt) and target trace(tt) was changed, rt= 2*green window and tt = half of distance from 'f' to green markers
       -if the 'f' mark is set the reference to correlate window is taken from it and the size is defined as half of the distance to the green markers (fine adjustment)
       -mark the traces as not saved after do the correlation
    PICKING:
       -insert componets R and T

2018-05-10 21:50 UTC, marcelobianchi commented on mblibgr/basic.c
> +	int X, Y, screenNo;
Esse não é aparente o modo de fazer isso. Teria que usar uma extensão do xrandr, ou seja usando a libxrand. Desfazer essas modificações.

2018-05-10 22:00 UTC, marcelobianchi requested changes
Israel, tem coisas que estão bem, mas tem bastante coisa para limpar no código e coisas que não estão de acordo que podem dar problema no futuro. Não são coisas difíceis de arrumar mas tem que ser feitas para poder integrar.

2018-05-10 22:00 UTC, marcelobianchi commented on mblibsac/sachead.h
> +	/// Low pass filter S
Esse arquivo não é específico do sacinspect, logo esses comentários não são apropriados. Reverter para a versão no repositório neste arquivo.

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/PK.c
> +/*        fprintf(stderr,"%s %f %d %d\n", d->files[j].current->head->kstnm, TfMark, t_jstart, t_npts);*/
remover esses comentários ...

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/PK.c
> +/*		fprintf(stderr,"%s lags %f ",d->files[j].current->head->kstnm, *lags);*/
e esse ....

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/PK.c
> +/*		fprintf(stderr," ni %d i %d  xmax  %f\n",n_index, index, xmax);*/
e esse

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/PK.c
> +/*		}*/
Remover completamente ao invés de deixar comentado.

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/io.c
> +/*		fprintf(stdout,"hello \n");*/
Limpar os comentários.

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/io.c
> +/*		// Check that this is a N file*/
limpar ...

2018-05-10 22:00 UTC, marcelobianchi commented on sacinspect/io.c
> +		if (getConfigAsNumber(config, NAME_PICK, DEFAULT_PICK) == P)
Acho que aqui esta complicado. O problema todo é que se você carrega as outras componentes, voce le os filtros da T ou da Z dependendo se você esta picando P ou S. Acho que as coisas deveriam ser independentes e, provavelmente se você estiver fazendo leitura de S. Temos que trabalhar melhor isso antes de poder integrar.

2018-05-11 22:07 UTC, IsraelDragone commented on sacinspect/io.c
> +		if (getConfigAsNumber(config, NAME_PICK, DEFAULT_PICK) == P)
Alguma sugestão de como deixar isso melhor? As demais questões já corrigi

2018-05-18 14:06 UTC, marcelobianchi commented on sacinspect/io.c
> +		if (getConfigAsNumber(config, NAME_PICK, DEFAULT_PICK) == P)
Eu tiraria de dentro desse IF que esta decidindo se carrega todas e colocaria um if abaixo, se a fase é P carrega da Z se a fase é S carrega da T se ele tiver sido carregada, senao tem que dar um erro.

2018-06-07 20:57 UTC, marcelobianchi approved these changes

2018-06-07 20:57 UTC, merged